### ISSUE TITLE
View Bank account not working

### ISSUE THREAD

**Issue by Peple77** [Renewed-Scripts/Renewed-Banking#12]
Whenever I press View Bank Account it does the animation and the progressbar but my mouse just pops up and no ui, Manage accounts works tho

**Comment by itsHyper** [comment]
You're probably downloading the ZIP code and installing it that way, You need to install the release through github and install it that way

**Comment by Temouchenty** [comment]
i got the same issue here

**Comment by NotPhelps** [comment]
@Temouchenty @Peple77 https://github.com/Renewed-Scripts/Renewed-Banking/releases/download/v1.0.3/Renewed-Banking.rar
