### ISSUE TITLE
Replace of qb-management 

### ISSUE THREAD

**Issue by Iitsmemitchell** [Renewed-Scripts/Renewed-Banking#13]
Dear Renewed,

I've read that it stated this resource will replace qb-management. I understand with the whole gang and jobs being done in the phone now with renewed-phone but if we remove qb-management; do we still be able to have a boss stash, gang stash etc? 

Because i think these options are gone than, if so; do any of you have a smart way of making a stash for bosses jobs/gangs ?

**Comment by mhnl3** [comment]
You can replace the functions in qb-management for getting/adding/removing the money with the new exports

**Comment by Iitsmemitchell** [comment]
Appreciated, will do! Issue solved 💪🏼
