### ISSUE TITLE
Not enough money on account

### ISSUE THREAD

**Issue by Iitsmemitchell** [Renewed-Scripts/Renewed-Banking#14]
When you don't have enough money in the account your trying to withdraw or deposit money to/from it will display an error saying account has insufficated funds but the loading screen just doesn't end loading. Only way to get rid of it is by restarting the renewed-banking script. 

![image](https://user-images.githubusercontent.com/86323279/192135161-07d12b08-deb1-4fdc-ab5f-cdb86b72f5c3.png)

**Comment by uShifty** [comment]
This issue was resolved with #19
