### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by AndreasFromDanmark** [Renewed-Scripts/Renewed-Banking#15]
Where do i add this?

![image](https://user-images.githubusercontent.com/35656492/193377943-629b20db-581a-45cd-8dd9-bf6ff368a8e0.png)

**Comment by doritohead** [comment]
Pretty sure thats just if you want to intergrate it into other scripts

**Comment by AndreasFromDanmark** [comment]
@doritohead Ah okay 👍
