### ISSUE TITLE
UI panel showing as undefined

### ISSUE THREAD

**Issue by Riggsee** [Renewed-Scripts/Renewed-Banking#17]
When opening the banking UI all of the text and interactions appear as "undefined" 

Maybe I'm starting something out of order or something like that but not too sure. 

https://i.imgur.com/awYpQa3.png

**Comment by uShifty** [comment]
Are you using the latest QBCore? Also did you change anything in any of the locales that could cause it not send the translations to the UI? You should join the discord as I will be able to assist you their quicker https://discord.gg/P3RMrbwA8n
