### ISSUE TITLE
[Issue] Showing Multi-Account 

### ISSUE THREAD

**Issue by SoStressful** [Renewed-Scripts/Renewed-Banking#20]
Found a "issue" with banking. It's not really an issue but I could see people bringing it up. If you are in a gang and the "Boss" of two businesses then the menu will only show 3 options unless you sign into the other job. 

![L4uZ3ZL](https://user-images.githubusercontent.com/69329555/195264236-b0530b19-f4a8-499d-9763-5950e16d44d5.png)
![0TO8ZdC](https://user-images.githubusercontent.com/69329555/195264242-6494acb3-2164-4ff8-9417-e265f05657d6.png)

**Comment by uShifty** [comment]
Ill add this to my list for the next update I keep forgetting sorry about that

**Comment by uShifty** [comment]
Should be resolved whenever I push the next update #27
