### ISSUE TITLE
ui freezes after progressbar

### ISSUE THREAD

**Issue by itsluap** [Renewed-Scripts/Renewed-Banking#23]
tried figuring it out on my own but it doesn't give an error, it sends the nui message and everything works just no bank ui

**Comment by uShifty** [comment]
Download from the [releases](https://github.com/Renewed-Scripts/Renewed-Banking/releases/download/v1.0.3/Renewed-Banking.rar) not the source code,

**Comment by itsluap** [comment]
i'm on v1.0.3 and it's happening

**Comment by itsluap** [comment]
any chance it's from using a different multicharacter?

**Comment by uShifty** [comment]
It can be, try with latest qb multicharacter and spawn

**Comment by itsluap** [comment]
It does still happen with the latest qb-multicharacter. Going to do further testing to see if I can figure out why it's happening

**Comment by itsluap** [comment]
Update: Using v1.0.2 fixed it, still couldn't figure out what was causing it though.
