### ISSUE TITLE
Progressbar not working

### ISSUE THREAD

**Issue by AndreasFromDanmark** [Renewed-Scripts/Renewed-Banking#36]
I dont know

![image](https://user-images.githubusercontent.com/35656492/226135421-626012e3-d81e-44e3-abe8-e5f4e5013102.png)

**Comment by uShifty** [comment]
We are now using ox lib to handle progress bars so this is out of date. Download 2.0 and try again. If you encounter any issues contact me at https://discord.gg/P3RMrbwA8n
