### ISSUE TITLE
Error when clicking manage account

### ISSUE THREAD

**Issue by pepski1270** [Renewed-Scripts/Renewed-Banking#40]
![image](https://user-images.githubusercontent.com/104223970/230601738-25b2ffde-777a-48b4-a6af-ff003a226d63.png)
using ox lib and ox target

**Comment by uShifty** [comment]
qb menu is no longer supported so this issue shouldnt happen in the new 2.0 release. If you encounter any problems contact me on discord at https://discord.gg/P3RMrbwA8n
