### ISSUE TITLE
Bank transfers only work with uppercase

### ISSUE THREAD

**Issue by ChickenDipper1** [Renewed-Scripts/Renewed-Banking#41]
As the title, bank transfers will only work if the CID is uppercase, if not the money vanishes :)

**Comment by NupNipz** [comment]
Change yoour "handleTransaction" function on the server side to this 
`local function handleTransaction(account, title, amount, message, issuer, receiver, type, transID)
    local transaction = {
        trans_id = transID or genTransactionID(),
        title = title,
        amount = amount,
        trans_type = type,
        receiver = receiver,
        message = message,
        issuer = issuer,
        time = os.time()
    }
    if cachedAccounts[account:upper()] then
        table.insert(cachedAccounts[account:upper()].transactions, 1, transaction)
        MySQL.query("INSERT INTO bank_accounts_new (id, transactions) VALUES (:id, :transactions) ON DUPLICATE KEY UPDATE transactions = :transactions",{
            ['id'] = account,
            ['transactions'] = json.encode(cachedAccounts[account:upper()].transactions)
        })
    elseif cachedPlayers[account:upper()] then
        table.insert(cachedPlayers[account:upper()].transactions, 1, transaction)
        MySQL.query("INSERT INTO player_transactions (id, transactions) VALUES (:id, :transactions) ON DUPLICATE KEY UPDATE transactions = :transactions",{
            ['id'] = account:upper(),
            ['transactions'] = json.encode(cachedPlayers[account:upper()].transactions)
        })
    else
        print(Lang:t("logs.invalid_account",{account=account:upper()}))
    end
    return transaction
end exports("handleTransaction", handleTransaction)`

**Comment by ChickenDipper1** [comment]
Thanks very much, I moved back to qb banking waiting a fix so will give this a go!

**Comment by uShifty** [comment]
This was fixed in 2.0 update, btw his fix wasnt even right 😂😂 Anyways if you still encounter this problem contact me on discord at https://discord.gg/P3RMrbwA8n
