### ISSUE TITLE
Business accounts - Transactions

### ISSUE THREAD

**Issue by Pilpest** [Renewed-Scripts/Renewed-Banking#42]
![image](https://user-images.githubusercontent.com/69690664/234782690-75c2eba4-d74d-4378-8625-6a00f5ca6898.png)
![image](https://user-images.githubusercontent.com/69690664/234783001-a4133120-7b72-4a2b-8584-b3ba4c02da77.png)

When performing any sort of transaction on a business account example 'police' the information displays appropriately, but you can not re-open the bank afterward due to this error.

**Comment by uShifty** [comment]
Should be fixed now with the 2.0 update, if it is not contact me on discord https://discord.gg/P3RMrbwA8n
