### ISSUE TITLE
Missing checks ?

### ISSUE THREAD

**Issue by OfficialRDB** [Renewed-Scripts/Renewed-Banking#8]
**Transfer**
I'm in a loading loop if I leave business / gang account or citizen id empty or if I fill in random id's or business names.
```
- Citizen ID to check if the person is online and or the ID does exist.
- Does the business / gang account exist.
```	
**Withdraw**
```
- I'm able to withdraw 0
- I'm able to withdraw minus amounts that will give you positive balance
```

**Comment by uShifty** [comment]
Unable to reproduce any of these excepting withdrawing 0 but that can be fixed. I suggest you join the discord as I can provide support faster on it :) discord.gg/P3RMrbwA8n
