### ISSUE TITLE
Strange Issue

### ISSUE THREAD

**Issue by KrnkTV** [Renewed-Scripts/Renewed-Banking#9]
When i trying to open atm or bank i just receive this
![Screenshot_17](https://user-images.githubusercontent.com/82491495/191320510-bbfef02c-f454-4b6b-985b-261657c6e10e.png)
And UI dont pop up just my mouse stuck on screen

I use QBCore downloading before 2 days

0 changes on Banking Script

**Comment by FjamZoo** [comment]
U need to download the Packaged version not the source code you can find the right donwload here https://github.com/Renewed-Scripts/Renewed-Banking/releases/tag/v1.0.2
